### ISSUE TITLE
Consider alternative for Level property

### ISSUE THREAD

**Issue by anarchivist** [RockefellerArchiveCenter/rac-data-model#1]
I think using `rdfs:label` will have unintended consequences if you use it for Level as you're using it for `pcdm:Collection` and `pcdm:Object`. This property is intended for use to provide a human readable name for a resource.

A couple alternatives: 

* The [ReLoad project](https://labs.regesta.com/progettoReload/en) uses [`oad:has_level`](http://lod.xdams.org/reload/oad/has_level), which has the range of [`oad:levelOfDescription`](http://lod.xdams.org/reload/oad/levelOfDescription). [Resources of that type](https://sparqlclient.eionet.europa.eu/sparqlClient.action?endpoint=http%3A%2F%2Flod.xdams.org%2Fsparql&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0A%0D%0ASELECT+DISTINCT+%3Fsubject+%3Flabel%0D%0AWHERE+%7B%0D%0A++%3Fsubject+a+%3Chttp%3A%2F%2Flod.xdams.org%2Freload%2Foad%2FlevelOfDescription%3E%0D%0A++OPTIONAL+%7B%0D%0A++++%3Fsubject+rdfs%3Alabel+%3Flabel%0D%0A+++++FILTER%28LANG%28%3Flabel%29+%3D+%22%22+%7C%7C+LANGMATCHES%28LANG%28%3Flabel%29%2C+%22en%22%29%29%0D%0A++%7D%0D%0A%7D&execute=Execute&_sourcePage=oXevu5KIY0gu2H4d1dUhMXPAc_qpOSnr0jZb-QGf1io%3D&__fp=1Mjv0_5PbqE%3D) map to the EAD `level` attribute values; `otherlevel` as you can imagine is a little weirder. They also directly map using `owl:sameAs` to concepts in the SAA glossary.
* Archives Hub (for LOCAH and Linking Lives) used [`locah:level`](http://data.archiveshub.ac.uk/def/level) with range [`locah:Level`](http://data.archiveshub.ac.uk/def/Level). [Those resources](https://sparqlclient.eionet.europa.eu/sparqlClient.action;jsessionid=424DCBA8669ED3E65BCE005BEB6CD175?endpoint=http%3A%2F%2Fdata.archiveshub.ac.uk%2Fsparql&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0A%0D%0ASELECT+DISTINCT+%3Fsubject+%3Flabel%0D%0AWHERE+%7B%0D%0A++%3Fsubject+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23inScheme%3E+%3Chttp%3A%2F%2Fdata.archiveshub.ac.uk%2Fid%2Fconceptscheme%2Fhublevels%3E%0D%0A++OPTIONAL+%7B+%3Fsubject+rdfs%3Alabel+%3Flabel+%7D%0D%0A%7D+&execute=Execute) are similar to ReLoad's resources (ie. they're based on EAD levels), with the major difference  being that 1) it's a more constrained subset and 2) the vocab is expressed using SKOS.

**Comment by p-galligan** [comment]
Yeah, this was the one value that we were talking about the the most, and hadn't come across the different options.

We'll definitely take a look at these options, they both look very promising. Thanks!

**Comment by p-galligan** [comment]
Changed to oad:has_level
