### ISSUE TITLE
Multiple languages for a collection or object?

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac-data-model#14]
Decide whether we want to allow multiple language associations for a collection or object?

If so, document and reflect that ability in the data model.

**Comment by helrond** [comment]
The data model currently allows for multiple languages to be associated with collections and objects. This is probably a good idea and something we want to allow, even if we don't currently have tooling to make it happen.

**Comment by p-galligan** [comment]
I agree that this is something we should allow. It's feasible that a collection could have multiple languages in the future. AS currently only allows one language, though.
