### ISSUE TITLE
Multiple Extents

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac-data-model#16]
Currently the model has a maximum of one extent, but the JSON responses drafted up allow for multiple.

Need to clarify whether we want to allow multiple extents in the model.

**Comment by p-galligan** [comment]
EAD and archival description allows for multiple extents. I think it makes sense to allow for these in the data model.

**Comment by helrond** [comment]
I agree - I think multiple extents are desirable. Which leads me to wonder if we need some way of distinguishing between them, just like dates have a label?
