### ISSUE TITLE
Break schema into multiple files for different object types

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac-data-model#20]
Break up the schema so we can validate against each object type.

**Comment by helrond** [comment]
1ae5ff42b2d765b357e2ef36145e73e10a0a1e95 somewhat alleviates the need for this right now, but we may want to consider the order of keys in definitions (perhaps alphabetical?). It can be hard to figure out where a particular definition is in the list.

**Comment by helrond** [comment]
Closing, as this has been addressed.
