### ISSUE TITLE
Decide whether floats should be string or number

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac-data-model#27]
JSON does not specify whether or not floating point values should be encoded as strings or numbers. There appear to be some (edge-casey?) reasons for using a string, but would be good to do a bit of research and get a better sense of what to do. See also https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number

**Comment by p-galligan** [comment]
Fixed by #30
