### ISSUE TITLE
pcdm:File - use of edm:uri

### ISSUE THREAD

**Issue by anarchivist** [RockefellerArchiveCenter/rac-data-model#3]
Can you help me understand the decision to use`edm:uri` for `pcdm:File`? `edm:uri` is essentially a [soft-deprecated property](https://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_Documentation//EDM_Definition_v5.2.8_102017.pdf#page=42).

**Comment by p-galligan** [comment]
Changed to owl:sameAs since we're trying to indicate the web resource link is the same as the digital file.
