### ISSUE TITLE
Clarify when to nest objects within objects

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac-data-model#9]
The data model allows for nesting of objects within objects, not just collections. We will need to make a decision about when to do that and document that decision within the data model.

**Comment by helrond** [comment]
I think there are a couple ways to do this:
1. map ArchivesSpace resources to collections and archival objects to objects
2. make the highest entity in a tree (ie the thing without any parents) a collection, and everything else an object
3. make everything that has children a collection, and everything else an object.

My instinct is #3 is the most semantically meaningful and realistic to model, but would be interested in other opinions...
